engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.md"
exclude_paths:
- test/
- node_modules/
- web/
