branches:
  except:
  - gh-pages
sudo: false
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
- CXX=g++-4.8
language: node_js
node_js:
- '7'
- '8'
before_install:
- npm config set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: Yv5+82+mD5lJBvYkr+gKIvpgM7wAC+sb2eezI5Q+iFtRcHfx+0LNimwm0zT4OzX2cspnfJMJq/EPQtswMa2Jx0OVB8pVt6r8SeRHkahJDIHjKf3oUV0YulgF5R7HV60J3iLLf8EolQAcKP8Rakbf5VgZj65OWlURV6foue4HEjA=
