# blacklist
branches:
  except:
    - gh-pages
sudo: false
# zopfli needs C++11 extensions, circa 10/15 those are easier found in Travis w/clang
env: CC=clang CXX=clang
language: node_js
node_js:
  - "4.2"
before_script:
  - npm install -g grunt-cli
