branches:
  except:
  - gh-pages
os: linux
dist: trusty
git:
  depth: 8
  submodules: false
cache:
  directories:
  - node_modules
language: node_js
node_js:
- '11'
- '12'
before_install:
- curl -LO "https://github.com/google/zopfli/archive/zopfli-1.0.2.zip" && unzip zopfli-1.0.2.zip
- cd zopfli-zopfli-1.0.2 && make
- chmod +x zopfli && export PATH="$(pwd):${PATH}"
- cd  ..
- npm config set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: R+8ByBe4ykDU7FbFnDWqNn14zP+YiHH2ULrQa4LB5ym16LbPjwf2mKUD6fAacrqxVYi84S9G8ZfmnzYIijAF2UQO8nh2Z6SuLvLv4iReexWjdtmMoVuOtMNMilyPUmvflPeLp6gW1V1ze8cNpWJ4MSOUAY8N/OIarqVoBGnIMs8=
